openapi: 3.0.0
info:
  title: Origin Backend Take-Home Assignment
  description: |-
    Origin offers its users an insurance package personalized to their specific needs without
    requiring the user to understand anything about insurance. This allows Origin to act as their
    de facto insurance advisor.
  contact: { }
  version: '1.0'
servers:
  - url: 'http://localhost:7000/'
    variables: { }
paths:
  /calculate:
    post:
      tags:
        - insurance
      summary: >
        Endpoint that receives a JSON payload with the user information and returns her risk profile
        (JSON again) – you don’t have to worry about the frontend of the application.
      operationId: calculateInsuranceAdvisor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInformation'
        required: true
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RiskEvaluation'
components:
  schemas:
    UserInformation:
      required:
        - age
        - dependents
        - income
        - marital_status
        - risk_questions
      type: object
      properties:
        age:
          type: integer
        dependents:
          type: integer
        house:
          $ref: '#/components/schemas/House'
        income:
          type: integer
        marital_status:
          type: string
          enum:
            - married
            - single
        risk_questions:
          type: array
          items:
            type: boolean
        vehicle:
          $ref: '#/components/schemas/Vehicle'

    House:
      required:
        - ownership_status
      type: object
      properties:
        ownership_status:
          type: string
          enum:
            - owned
            - mortgaged
    Vehicle:
      required:
        - year
      type: object
      properties:
        year:
          type: integer
    RiskEvaluation:
      required:
        - auto
        - disability
        - home
        - life
      type: object
      properties:
        auto:
          $ref: '#/components/schemas/InsuranceScore'
        disability:
          $ref: '#/components/schemas/InsuranceScore'
        home:
          $ref: '#/components/schemas/InsuranceScore'
        life:
          $ref: '#/components/schemas/InsuranceScore'
    InsuranceScore:
      type: string
      enum:
        - ineligible
        - economic
        - regular
        - responsible

